# Generated by Django 4.2.3 on 2023-07-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.URLField()),
                ('year', models.PositiveIntegerField()),
                ('run_time', models.CharField(max_length=20)),
                ('star', models.DecimalField(decimal_places=1, max_digits=2)),
                ('count', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_watched', models.BooleanField()),
                ('genres', models.ManyToManyField(related_name='movies', to='app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_finished', models.BooleanField()),
                ('movies', models.ManyToManyField(related_name='collections', to='app.movie')),
            ],
        ),
    ]
