# Generated by Django 4.2.3 on 2023-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='app.movie'),
        ),
    ]
