# Generated by Django 4.2.3 on 2023-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_collection_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
