# Generated by Django 4.2.3 on 2023-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_collection_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(related_name='movies', to='app.collection'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
