# Generated by Django 4.2.3 on 2023-07-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_collection_movies_movie_collections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(related_name='movie', to='app.collection'),
        ),
    ]
