# Generated by Django 4.2.3 on 2023-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_movie_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(related_name='movies', to='app.collection'),
        ),
    ]
